# Generated by Django 4.2.4 on 2023-08-08 10:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated At')),
                ('deleted', models.BooleanField(default=False)),
                ('company_id', models.CharField(help_text='Company ID', max_length=128)),
                ('name', models.CharField(help_text='Name', max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
