# Generated by Django 4.2.4 on 2023-08-16 08:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryForSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated At')),
                ('deleted', models.BooleanField(default=False)),
                ('inventory_id', models.UUIDField(help_text='Inventory UUID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price', max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated At')),
                ('deleted', models.BooleanField(default=False)),
                ('customer', models.UUIDField(help_text='Customer')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity')),
                ('inventory', models.ForeignKey(help_text='Inventory for sale', on_delete=django.db.models.deletion.CASCADE, to='orders.inventoryforsale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
