# Generated by Django 4.2.4 on 2023-08-08 12:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Margin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated At')),
                ('deleted', models.BooleanField(default=False)),
                ('country_id', models.UUIDField(help_text='Country UUID')),
                ('percent', models.PositiveIntegerField(help_text='Percent', validators=[django.core.validators.MinValueValidator])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated At')),
                ('deleted', models.BooleanField(default=False)),
                ('product_id', models.UUIDField(help_text='Product UUID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price', max_digits=7)),
                ('customer', models.ForeignKey(help_text='Customer', on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
