# Generated by Django 4.2.4 on 2023-08-16 08:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryForSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated At')),
                ('deleted', models.BooleanField(default=False)),
                ('inventory_id', models.UUIDField(help_text='Inventory UUID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price', max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Margin',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.UUIDField(help_text='Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='inventory',
            field=models.ForeignKey(default=django.utils.timezone.now, help_text='Inventory for sale', on_delete=django.db.models.deletion.CASCADE, to='orders.inventoryforsale'),
            preserve_default=False,
        ),
    ]
