# Generated by Django 4.2.4 on 2023-08-18 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryforsale',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
